// Episode 1 DM scene index. Notes are brief original summaries, not adventure text reproductions.
export const episodeScenes = [
 {id:'warehouse',name:'The Ruined Warehouse',type:'image',src:'./assets/episode1/warehouse.jpg',note:'Investigation begins here. A rope leads from the collapsed warehouse into the fissure. Allow exploration before descent.'},
 {id:'fissure',name:'Fissure Descent — 3D',type:'live',note:'Use Warehouse / Area 1 controls and Explore mode for a live descent. The shaft depth in MapForge is adjustable.'},
 {id:'rats',name:'Area 1 · Rats',type:'image',src:'./assets/episode1/area1.jpg',note:'Rats in the debris-filled passage; human footprints lead north. The fissure opens along the west wall near the chamber.'},
 {id:'trials',name:'Area 2 · Trials',type:'room3d',src:'./assets/episode1/area2.jpg',note:'Presentation cue: intact worked-stone hall, six columns and buttresses, four distinct pools (blue, green, clear, cloudy), wall carvings of robed figures submerging themselves, and an ornate locked double door. Keep pool effects hidden until play reveals them.'},
 {id:'traps',name:'Area 3 · Traps',type:'room3d',src:'./assets/episode1/area3.jpg',note:'Presentation cue: long east-running passage, broad central stretch, subtle scorch/rune evidence, and ornate double doors at the far end. Do not show trap letters or hidden trigger information to players.'},
 {id:'tunnels',name:'Area 4 · Tunnels',type:'card',caption:'Beneath Waterdeep, the passages wind through ancient stone.',note:'Presentation cue: earthquake-damaged maze, cave-in debris, overgrown blood weeds, and an acid pit with floating bones. This area benefits more from cinematic transition art than a full tactical 3D maze.'},
 {id:'death',name:'Area 5 · Death',type:'room3d',src:'./assets/episode1/area5.jpg',note:'Presentation cue: natural cavern, ceiling lost in thick dusty webs, five hanging cocoons (two suspiciously humanoid), and a giant spider concealed in a dusty floor depression.'},
 {id:'goblin',name:'Area 6 · Goblin',type:'room3d',caption:"A goblin’s voice echoes through the darkness.",note:'Presentation cue: frightened Gorkoh emerges from behind a stalagmite, bluffing with a gnarled bleached-wood “wand.” A heap of bones and gear is visible northeast; a fragile sharp stalactite cluster marks the way onward.'},
 {id:'stomp',name:'Area 7 · Stomp',type:'room3d',caption:'Something enormous moves beneath the cavern floor.',note:'Presentation cue: the chamber is littered with many severed bare feet; the suspended granite Big Foot dominates the space; rune-graven footprint motifs appear on the north and south walls.'},
 {id:'tentacle',name:'Area 8 · Tentacle',type:'room3d',caption:'The stench of sewage rises from the black water.',note:'Presentation cue: round sewer chamber, ceiling pipes pouring dirty brown sewage into a massive cesspool, a narrow perimeter walkway, and one enormous tentacle disturbing the deeper center.'},
 {id:'dragon',name:'Area 9 · Dragon',type:'room3d',caption:'Deep within the cave, a dragon stirs.',note:'Presentation cue: Dabshabah is a wounded young brass dragon pinned beneath earthquake rubble and struggling to breathe; two darkmantles wait overhead out of reach. Frame this as a rescue/uncertain encounter, not a boss fight.'},
 {id:'shrine',name:'Area 10 · Shrine of Destruction',type:'room3d',caption:'At the end of the tunnels, ancient magic pulses around a shattered shrine.',note:'Presentation cue: rune-covered granite altar, battered six-sided Orrery housing with missing side plates, damaged entropy guardian above it, Sergeant Teeshe resting in the southwest corner, and Caerhan’s body nearby. Do not visually reveal hidden possession information.'},
 {id:'return',name:'Return to Waterdeep',type:'card',caption:'The city waits above. Your first mission is nearly complete.',note:'Return from the fissure, report the investigation, and wrap Episode 1. Use the conclusion in the source.'}
];